lien_musique: https://www.youtube.com/watch?v=RwFs8hE1yD8
lien_pdf_choregraphie: https://firebasestorage.googleapis.com/v0/b/danse-musique-laille.appspot.com/o/dances%2F89b34d7e-6d89-4342-80b8-1fd64c2980ec%2Fchoreography.pdf?alt=media&token=451c4e39-e391-4a45-830f-08d909b9dd26
lien_video_choregraphie: https://www.youtube.com/watch?v=cY0KdNt6FVU
nom: 'Train Wreck '
